"""Detector and electronics: white noise, 1/f noise, gain nonlinearity, ADC.

All stochastic functions require an explicit ``numpy.random.Generator`` —
there is no module-level RNG and no default seed (plan §11: no
non-reproducible behavior)."""

from __future__ import annotations

import numpy as np


def white_noise(rng: np.random.Generator, n: int, sigma: float) -> np.ndarray:
    """Additive white Gaussian noise, standard deviation ``sigma``."""
    return rng.normal(0.0, sigma, n)


def one_over_f_noise(
    rng: np.random.Generator,
    n: int,
    sigma: float,
    slope: float = 1.0,
) -> np.ndarray:
    """Additive 1/f^slope noise with total standard deviation ``sigma``.

    Generated by spectral shaping: white Gaussian spectrum multiplied by
    f^(-slope/2), inverse FFT, then normalized to the requested sigma.
    (Timmer & Koenig method; J. Timmer, M. Koenig, "On generating power law
    noise", Astron. Astrophys. 300 (1995) 707.) The DC bin is zeroed.
    """
    if n < 2:
        raise ValueError("n must be >= 2")
    freqs = np.fft.rfftfreq(n, d=1.0)
    shaping = np.zeros_like(freqs)
    shaping[1:] = freqs[1:] ** (-slope / 2.0)
    re = rng.normal(0.0, 1.0, len(freqs))
    im = rng.normal(0.0, 1.0, len(freqs))
    spectrum = (re + 1j * im) * shaping
    spectrum[0] = 0.0
    noise = np.fft.irfft(spectrum, n=n)
    std = noise.std()
    if std > 0.0:
        noise = noise * (sigma / std)
    return noise


def gain_nonlinearity(signal: np.ndarray, quadratic_rel: float) -> np.ndarray:
    """Memoryless second-order gain compression/expansion.

    out = s + c * s^2  (s in relative full-scale units; c is the relative
    deviation from linear response at full scale).
    """
    return signal + quadratic_rel * signal * signal


def adc_quantize(
    signal: np.ndarray,
    bits: int,
    full_scale: float,
) -> np.ndarray:
    """Uniform mid-tread quantization of an ADC with ``bits`` resolution.

    Input range [0, full_scale] maps to 2**bits levels; values outside are
    clipped (saturation).
    """
    if bits < 1:
        raise ValueError("bits must be >= 1")
    levels = 2**bits - 1
    step = full_scale / levels
    clipped = np.clip(signal, 0.0, full_scale)
    return np.round(clipped / step) * step
