"""Detector and electronics: white noise, 1/f noise, gain nonlinearity, ADC.

All stochastic functions require an explicit ``numpy.random.Generator`` —
there is no module-level RNG and no default seed (plan §11: no
non-reproducible behavior)."""

from __future__ import annotations

import numpy as np


def white_noise(rng: np.random.Generator, n: int, sigma: float) -> np.ndarray:
    """Additive white Gaussian noise, standard deviation ``sigma``."""
    return rng.normal(0.0, sigma, n)


def one_over_f_noise(
    rng: np.random.Generator,
    n: int,
    sigma: float,
    slope: float = 1.0,
) -> np.ndarray:
    """Additive 1/f^slope noise with total standard deviation ``sigma``.

    Generated by spectral shaping: white Gaussian spectrum multiplied by
    f^(-slope/2), inverse FFT, then normalized to the requested sigma.
    (Timmer & Koenig method; J. Timmer, M. Koenig, "On generating power law
    noise", Astron. Astrophys. 300 (1995) 707.) The DC bin is zeroed.
    """
    if n < 2:
        raise ValueError("n must be >= 2")
    freqs = np.fft.rfftfreq(n, d=1.0)
    shaping = np.zeros_like(freqs)
    shaping[1:] = freqs[1:] ** (-slope / 2.0)
    re = rng.normal(0.0, 1.0, len(freqs))
    im = rng.normal(0.0, 1.0, len(freqs))
    spectrum = (re + 1j * im) * shaping
    spectrum[0] = 0.0
    noise = np.fft.irfft(spectrum, n=n)
    std = noise.std()
    if std > 0.0:
        noise = noise * (sigma / std)
    return noise


def gain_nonlinearity(
    signal: np.ndarray,
    quadratic_rel: float,
    cubic_rel: float = 0.0,
    saturation_level: float = 0.0,
) -> np.ndarray:
    """Memoryless polynomial gain compression/expansion with optional saturation.

    out = s + c2*s^2 + c3*s^3, then soft-clipped at saturation_level if > 0.
    The cubic term models asymmetric distortion at high photocurrents.
    Saturation models detector/amplifier output clipping via tanh soft-clip.
    """
    out = signal + quadratic_rel * signal * signal
    if cubic_rel:
        out = out + cubic_rel * signal * signal * signal
    if saturation_level > 0:
        out = saturation_level * np.tanh(out / saturation_level)
    return out


def adc_quantize(
    signal: np.ndarray,
    bits: int,
    full_scale: float,
) -> np.ndarray:
    """Uniform mid-tread quantization of an ADC with ``bits`` resolution.

    Input range [0, full_scale] maps to 2**bits levels; values outside are
    clipped (saturation).
    """
    if bits < 1:
        raise ValueError("bits must be >= 1")
    levels = 2**bits - 1
    step = full_scale / levels
    clipped = np.clip(signal, 0.0, full_scale)
    return np.round(clipped / step) * step


def thermal_noise_scale(
    temperature_K: float,
    reference_temperature_K: float = 296.0,
) -> float:
    """Johnson-Nyquist thermal noise scaling factor.

    Thermal noise voltage scales as sqrt(T). Returns the multiplicative
    factor to apply to a noise sigma specified at T_ref to get the
    equivalent sigma at temperature T.

    sigma(T) = sigma(T_ref) * thermal_noise_scale(T, T_ref)
    """
    if temperature_K <= 0 or reference_temperature_K <= 0:
        raise ValueError("Temperature must be positive")
    return float(np.sqrt(temperature_K / reference_temperature_K))


def shot_noise(
    rng: np.random.Generator,
    signal: np.ndarray,
    gain: float = 1.0,
) -> np.ndarray:
    """Signal-dependent shot noise (Poisson statistics).

    Real photodetectors produce shot noise with variance proportional to
    the photocurrent (and thus to the optical signal). For large photon
    counts the Poisson distribution is well approximated by a Gaussian
    with sigma = sqrt(gain * |signal|).

    ``gain`` controls the noise magnitude: higher gain → more shot noise.
    Physically it lumps together detector quantum efficiency, transimpedance
    gain, and electronic-unit conversion. Typical relative values: 1e-4
    to 1e-3 for well-designed NIR TDLAS receivers.
    """
    sigma = np.sqrt(gain * np.abs(signal))
    return rng.normal(0.0, 1.0, len(signal)) * sigma


def periodic_interference(
    rng: np.random.Generator,
    n: int,
    frequencies_Hz: list[float],
    amplitudes_rel: list[float],
    scan_rate_Hz: float,
    n_points: int,
) -> np.ndarray:
    """Additive periodic interference from EMI/powerline/mechanical sources.

    Models 50/60 Hz harmonics, fan/pump vibration, and other periodic
    disturbances that appear as fixed-frequency sinusoids in the time
    domain of each scan. Phase is randomized per scan (captures
    asynchronous relationship between scan trigger and mains cycle).
    """
    t = np.arange(n) / (scan_rate_Hz * n_points)
    signal = np.zeros(n)
    for freq, amp in zip(frequencies_Hz, amplitudes_rel):
        phase = rng.uniform(0.0, 2.0 * np.pi)
        signal += amp * np.sin(2.0 * np.pi * freq * t + phase)
    return signal


def speckle_noise(
    rng: np.random.Generator,
    n: int,
    sigma: float,
    correlation_length: int = 10,
) -> np.ndarray:
    """Wavelength-correlated speckle noise from coherent illumination.

    In long-path or multi-pass TDLAS systems, laser speckle from rough
    surfaces (mirrors, cell walls) creates noise that is correlated across
    nearby spectral points. Modeled as filtered Gaussian noise with a
    configurable correlation length (in samples).
    """
    if correlation_length < 1:
        return rng.normal(0.0, sigma, n)
    raw = rng.normal(0.0, 1.0, n + correlation_length)
    kernel = np.ones(correlation_length) / np.sqrt(correlation_length)
    filtered = np.convolve(raw, kernel, mode="valid")[:n]
    std = filtered.std()
    if std > 0:
        filtered = filtered * (sigma / std)
    return filtered


def clock_jitter(
    rng: np.random.Generator,
    n: int,
    jitter_rel: float,
) -> np.ndarray:
    """ADC sampling clock jitter — fractional-sample timing perturbations.

    Returns an array of fractional index offsets that perturb the effective
    sample positions. The caller uses these to interpolate the signal onto
    the jittered grid, simulating the effect of clock instability on the
    effective frequency axis.
    """
    return rng.normal(0.0, jitter_rel, n)


def dark_current_noise(
    rng: np.random.Generator,
    n: int,
    sigma_ref: float,
    temperature_K: float,
    reference_temperature_K: float = 296.0,
    activation_energy_eV: float = 0.37,
) -> np.ndarray:
    """Temperature-dependent dark-current shot noise.

    Dark current in semiconductor photodetectors follows an Arrhenius
    temperature dependence: I_dark ~ exp(-Ea/(2*kB*T)). The shot noise
    from dark current scales as sqrt(I_dark), giving:

    sigma_dark(T) = sigma_ref * exp(-Ea/(2*kB) * (1/T - 1/T_ref))

    where Ea is the activation energy (~0.37 eV for InGaAs near 1.5 um
    cutoff, ~0.56 eV for Ge, ~0.18 eV for extended InGaAs).

    Parameters
    ----------
    sigma_ref : float
        Dark-current noise sigma at reference temperature.
    temperature_K : float
        Actual detector temperature.
    activation_energy_eV : float
        Bandgap-related activation energy. Default 0.37 eV (InGaAs).
    """
    kB_eV_per_K = 8.617333262e-5
    exponent = -activation_energy_eV / (2.0 * kB_eV_per_K) * (
        1.0 / temperature_K - 1.0 / reference_temperature_K
    )
    scale = float(np.exp(exponent))
    return rng.normal(0.0, sigma_ref * scale, n)
