"""Forward physics: HITRAN line data, line shapes, Beer-Lambert absorption."""

from .absorption import absorption_coefficient, line_strength_at_T, simulate_absorbance
from .hitran import (
    LineList,
    demo_ch4_2nu3,
    demo_co,
    demo_co2,
    demo_h2o,
    demo_hcl,
    demo_hf,
    demo_nh3,
    demo_no,
    demo_no2,
    demo_so2,
    fetch_lines,
)
from .lineshape import (
    doppler_hwhm_cm1,
    gaussian_profile,
    lorentz_hwhm_cm1,
    lorentz_profile,
    voigt_profile,
)
from .lineshape_htp import htp_profile
from .doas import (
    doas_optical_density,
    mie_extinction,
    number_density,
    polynomial_high_pass,
    rayleigh_cross_section,
    simulate_doas_cross_section,
    simulate_doas_spectrum,
)
from .ftir import (
    apodization_function,
    generate_interferogram,
    interferogram_to_spectrum,
    simulate_ftir_spectrum,
    spectral_resolution_cm1,
)
from .crds import (
    absorption_from_tau,
    cavity_finesse,
    empty_cavity_tau,
    fit_ring_down,
    nea_cm1,
    ring_down_time,
    ring_down_trace,
    simulate_crds_spectrum,
)
from .ndir import (
    bandpass_filter,
    ndir_detector_signal,
    ndir_ratio,
    planck_spectral_radiance,
    simulate_ndir,
)
from .tips import tips_q_ratio
from .wms import WMSConfig, lockin_demodulate, simulate_wms

__all__ = [
    "LineList",
    "WMSConfig",
    "absorption_coefficient",
    "absorption_from_tau",
    "apodization_function",
    "doas_optical_density",
    "bandpass_filter",
    "cavity_finesse",
    "empty_cavity_tau",
    "demo_ch4_2nu3",
    "demo_co",
    "demo_co2",
    "demo_h2o",
    "demo_hcl",
    "demo_hf",
    "demo_nh3",
    "demo_no",
    "demo_no2",
    "demo_so2",
    "doppler_hwhm_cm1",
    "fetch_lines",
    "fit_ring_down",
    "gaussian_profile",
    "generate_interferogram",
    "htp_profile",
    "interferogram_to_spectrum",
    "line_strength_at_T",
    "lockin_demodulate",
    "lorentz_hwhm_cm1",
    "lorentz_profile",
    "mie_extinction",
    "nea_cm1",
    "number_density",
    "ndir_detector_signal",
    "ndir_ratio",
    "planck_spectral_radiance",
    "polynomial_high_pass",
    "rayleigh_cross_section",
    "ring_down_time",
    "ring_down_trace",
    "simulate_absorbance",
    "simulate_crds_spectrum",
    "simulate_doas_cross_section",
    "simulate_doas_spectrum",
    "simulate_ftir_spectrum",
    "simulate_ndir",
    "simulate_wms",
    "spectral_resolution_cm1",
    "tips_q_ratio",
    "voigt_profile",
]
